# Generated by Django 5.2.5 on 2025-08-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id_layanan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_layanan', models.CharField(max_length=50)),
            ],
        ),
    ]
