# Generated by Django 5.2.5 on 2025-08-26 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisLayanan',
            fields=[
                ('id_jenis', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=50)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenis_layanan', to='layanan.layanan')),
            ],
        ),
    ]
