# Generated by Django 5.2.5 on 2025-10-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_jenislayanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenislayanan',
            name='tarif',
            field=models.IntegerField(),
        ),
    ]
