# Generated by Django 5.2.5 on 2025-08-26 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rumah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('rumah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penghuni', to='rumah.rumah')),
            ],
        ),
    ]
