# Generated by Django 5.2.5 on 2025-08-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_jenislayanan'),
        ('pelanggan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='aktif',
        ),
        migrations.CreateModel(
            name='Langganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.IntegerField()),
                ('aktif', models.BooleanField(default=True)),
                ('jenis_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.jenislayanan')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langganan', to='pelanggan.pelanggan')),
            ],
        ),
    ]
