# Generated by Django 5.2.5 on 2025-08-27 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0002_remove_pelanggan_aktif_langganan'),
        ('rumah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='rumah',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penghuni', to='rumah.rumah'),
        ),
    ]
