# Generated by Django 5.2.5 on 2025-10-17 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_jenislayanan'),
        ('pelanggan', '0003_alter_pelanggan_rumah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id_tagihan', models.AutoField(primary_key=True, serialize=False)),
                ('bulan', models.PositiveSmallIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')])),
                ('tahun', models.PositiveSmallIntegerField()),
                ('status_tagihan', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum', 'Belum Lunas')], default='Belum', max_length=10)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jenis_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.jenislayanan')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to='pelanggan.pelanggan')),
            ],
        ),
    ]
