# Generated by Django 5.2.5 on 2025-10-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0004_tagihan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagihan',
            name='jumlah_bayar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tagihan',
            name='status_tagihan',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Belum', 'Belum')], default='Belum', max_length=10),
        ),
    ]
