# Generated by Django 5.2.5 on 2025-08-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rumah',
            fields=[
                ('id_rumah', models.AutoField(primary_key=True, serialize=False)),
                ('rt', models.CharField(max_length=5)),
                ('no_rumah', models.CharField(max_length=10)),
                ('status_rumah', models.CharField(choices=[('dihuni', 'Dihuni'), ('kosong', 'Kosong'), ('lainnya', 'Lainnya')], default='kosong', max_length=10)),
            ],
            options={
                'unique_together': {('rt', 'no_rumah')},
            },
        ),
    ]
