# Generated by Django 5.2.5 on 2025-08-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumah',
            name='status_rumah',
        ),
    ]
