# Generated by Django 5.2.5 on 2025-08-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah', '0002_remove_rumah_status_rumah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='no_rumah',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
