# Generated by Django 5.2.5 on 2025-08-27 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layanan', '0002_jenislayanan'),
        ('pelanggan', '0002_remove_pelanggan_aktif_langganan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('bulan', models.PositiveSmallIntegerField()),
                ('tahun', models.PositiveSmallIntegerField()),
                ('status_bayar', models.CharField(choices=[('Sudah', 'Sudah Bayar'), ('Belum', 'Belum Bayar')], default='Belum', max_length=10)),
                ('tgl_pembayaran', models.DateField(blank=True, null=True)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jenis_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.jenislayanan')),
                ('kasir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='pelanggan.pelanggan')),
            ],
        ),
    ]
