# Generated by Django 5.2.5 on 2025-08-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='bulan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')]),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='status_bayar',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Belum', 'Belum Lunas')], default='Belum', max_length=10),
        ),
    ]
