# Generated by Django 5.2.5 on 2025-10-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0002_alter_pembayaran_bulan_alter_pembayaran_status_bayar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='jumlah_bayar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='status_bayar',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Belum', 'Belum')], default='Belum', max_length=10),
        ),
    ]
