# Generated by Django 5.2.5 on 2025-10-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0003_alter_pembayaran_jumlah_bayar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='tgl_pembayaran',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
